/* ============================================================
   Dofus Duel — DONNÉES (12 classes 1.29 complètes)
   Arsenal complet : 240 sorts réels, données Shivas/d2j_static
   ============================================================ */
var CLASSES = {
  iop: { n: 'Iop', icon: '⚔️', img: 'clofus.webp', hp: 360, el: 'Terre', mainStat: 'force',
    stats: { force: 30, intel: 10, chance: 10, agi: 10, vita: 40, sag: 15 },
    res: { Neutre: 0, Terre: 15, Feu: 0, Eau: 0, Air: -10 },
    style: 'melee', desc: 'Guerrier 1.29. Force brute : mêlée, buffs de dégâts, Bond, repousses, gros sorts Terre.',
    spells: [
      { id: 'pression', n: 'Pression', i: '👊', lvl: 1, cost: 2, min: 1, max: 2, d: [4,5], el: 'Terre', los: true, type: 'dmg', desc: 'Coup Terre de base' },
      { id: 'bond', n: 'Bond', i: '🌀', lvl: 1, cost: 5, min: 1, max: 6, el: 'Neutre', los: false, type: 'tp', desc: "Se téléporte jusqu'à 6 cases" },
      { id: 'intimidation', n: 'Intimidation', i: '💨', lvl: 1, cost: 2, min: 1, max: 1, d: [3,4], el: 'Neutre', los: true, type: 'dmg', push: 1, desc: 'Dégâts + repousse de 1 case' },
      { id: 'compulsion', n: 'Compulsion', i: '💪', lvl: 3, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 8, turns: 3 }, desc: '+8 dégâts pendant 3 tours' },
      { id: 'divine', n: 'Épée Divine', i: '⚜️', lvl: 6, cost: 3, min: 1, max: 1, d: [4,8], el: 'Air', los: true, type: 'dmg', selfZone: true, flat: { v: 3, turns: 2 }, desc: 'Dégâts Air autour de toi, +3 dégâts 2 tours' },
      { id: 'destin', n: 'Épée du Destin', i: '🌠', lvl: 9, cost: 4, min: 1, max: 1, d: [4,7], el: 'Feu', los: true, type: 'dmg', desc: 'Frappe Feu' },
      { id: 'guide', n: 'Guide de Bravoure', i: '🗡️', lvl: 13, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 6, turns: 3 }, desc: '+6 dégâts pendant 3 tours' },
      { id: 'amplification', n: 'Amplification', i: '🔥', lvl: 17, cost: 1, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 8, turns: 1 }, desc: '+8 dégâts ce tour' },
      { id: 'destructrice', n: 'Épée Destructrice', i: '💥', lvl: 21, cost: 4, min: 1, max: 2, d: [5,9], el: 'Feu', los: true, type: 'dmg', desc: 'Frappe Feu dévastatrice' },
      { id: 'couper', n: 'Couper', i: '⚔️', lvl: 26, cost: 3, min: 1, max: 3, d: [4,6], el: 'Feu', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Feu, la cible esquive moins les PA' },
      { id: 'souffle', n: 'Souffle', i: '🌪️', lvl: 31, cost: 2, min: 2, max: 8, el: 'Neutre', los: false, type: 'push', push: 2, desc: 'Repousse de 2 cases, sans dégâts' },
      { id: 'vitalite', n: 'Vitalité', i: '💚', lvl: 36, cost: 3, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'vita', vita: { v: 120, turns: 5 }, desc: '+120 PV max pendant 5 tours' },
      { id: 'jugement', n: 'Épée du Jugement', i: '⚡', lvl: 42, cost: 4, min: 1, max: 3, d: [6,11], el: 'Air', los: false, type: 'dmg', steal: 0.5, desc: 'Dégâts Air sans LoS, vole 50% des dégâts en PV' },
      { id: 'puissance', n: 'Puissance', i: '🔱', lvl: 48, cost: 4, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'powerPct', pct: { v: 0.5, turns: 3 }, desc: '+50% dégâts pendant 3 tours' },
      { id: 'mutilation', n: 'Mutilation', i: '🩸', lvl: 54, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 15, turns: 3 }, pct: { v: 0.25, turns: 3 }, desc: '+15 dégâts et +25% pendant 3 tours' },
      { id: 'tempete', n: 'Tempête de Puissance', i: '🌩️', lvl: 60, cost: 3, min: 3, max: 5, d: [12,15], el: 'Feu', los: true, type: 'dmg', desc: 'Rafale Feu' },
      { id: 'celeste', n: 'Épée Céleste', i: '✨', lvl: 70, cost: 4, min: 0, max: 4, d: [8,12], el: 'Air', los: true, type: 'dmg', aoe: 1, desc: 'Dégâts Air en zone (rayon 1)' },
      { id: 'concentration', n: 'Concentration', i: '🎯', lvl: 80, cost: 2, min: 1, max: 1, d: [4,7], el: 'Terre', los: true, type: 'dmg', desc: 'Frappe Terre rapide' },
      { id: 'epeedeiop', n: 'Épée de Iop', i: '🗡️', lvl: 90, cost: 4, min: 1, max: 4, d: [7,12], el: 'Terre', los: true, type: 'dmg', desc: "La grande frappe de l'Iop" },
      { id: 'colere', n: 'Colère de Iop', i: '😡', lvl: 100, cost: 6, min: 1, max: 1, d: [16,22], el: 'Terre', los: true, type: 'dmg', desc: "Le coup ultime de l'Iop (7 PA en 1.29, 6 ici)" }
    ] },
  cra: { n: 'Cra', icon: '🏹', img: 'clofus.webp', hp: 300, el: 'Air', mainStat: 'agi',
    stats: { force: 10, intel: 10, chance: 10, agi: 35, vita: 30, sag: 15 },
    res: { Neutre: 0, Terre: -10, Feu: 0, Eau: 0, Air: 15 },
    style: 'ranged', desc: 'Archer 1.29. Agilité : reste à distance, flèches variées, contrôle et poison.',
    spells: [
      { id: 'magique', n: 'Flèche Magique', i: '🏹', lvl: 1, cost: 4, min: 2, max: 9, d: [6,8], el: 'Feu', los: true, type: 'dmg', desc: 'Tir Feu de base' },
      { id: 'empoisonnee', n: 'Flèche Empoisonnée', i: '☠️', lvl: 1, cost: 4, min: 2, max: 7, d: [3,4], el: 'Neutre', los: true, type: 'dmg', poison: { d: 3, turns: 2 }, desc: 'Dégâts + poison 8 PV/tour pendant 2 tours' },
      { id: 'recul', n: 'Flèche de Recul', i: '💨', lvl: 1, cost: 4, min: 1, max: 5, d: [6,8], el: 'Air', los: true, type: 'dmg', push: 1, desc: 'Dégâts Air + repousse de 1 case' },
      { id: 'glacee', n: 'Flèche Glacée', i: '❄️', lvl: 3, cost: 3, min: 1, max: 7, d: [3,4], el: 'Feu', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Feu, la cible esquive moins les PA' },
      { id: 'enflammee', n: 'Flèche Enflammée', i: '🔥', lvl: 6, cost: 4, min: 1, max: 8, d: [7,8], el: 'Feu', los: true, type: 'dmg', push: 1, desc: 'Dégâts Feu + repousse' },
      { id: 'eloigne', n: 'Tir Éloigné', i: '👁️', lvl: 9, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'rangeUp', desc: '+2 portée pendant 3 tours' },
      { id: 'expiation', n: "Flèche d'Expiation", i: '🌠', lvl: 13, cost: 4, min: 6, max: 10, d: [11,13], el: 'Eau', los: true, type: 'dmg', desc: 'Flèche Eau de très longue portée' },
      { id: 'taupe', n: 'Œil de Taupe', i: '🦉', lvl: 17, cost: 3, min: 1, max: 7, d: [4,6], el: 'Air', los: true, type: 'dmg', steal: 0.5, subRange: 2, desc: 'Dégâts Air, vole 50% des dégâts, -2 portée cible' },
      { id: 'critique', n: 'Tir Critique', i: '🎯', lvl: 21, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'critUp', desc: '+15% critiques, +20% dégâts critiques 3 tours' },
      { id: 'immobilisation', n: "Flèche d'Immobilisation", i: '🪤', lvl: 26, cost: 2, min: 1, max: 8, d: [3,4], el: 'Eau', los: true, type: 'dmg', slow: true, desc: 'Dégâts Eau, cible -1 PM au prochain tour' },
      { id: 'punitive', n: 'Flèche Punitive', i: '🏹', lvl: 31, cost: 4, min: 5, max: 8, d: [10,12], el: 'Terre', los: true, type: 'dmg', push: 1, desc: 'Dégâts Terre + repousse' },
      { id: 'puissant', n: 'Tir Puissant', i: '⚡', lvl: 36, cost: 3, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'powerPct', pct: { v: 0.75, turns: 3 }, desc: '+75% dégâts pendant 3 tours' },
      { id: 'harcelante', n: 'Flèche Harcelante', i: '💫', lvl: 42, cost: 3, min: 1, max: 8, d: [4,6], el: 'Air', los: false, type: 'dmg', desc: 'Dégâts Air qui ignorent la ligne de vue' },
      { id: 'cinglante', n: 'Flèche Cinglante', i: '🌪️', lvl: 48, cost: 3, min: 1, max: 7, d: [4,5], el: 'Terre', los: true, type: 'dmg', slow: true, desc: 'Dégâts Terre, cible -1 PM au prochain tour' },
      { id: 'persecutrice', n: 'Flèche Persécutrice', i: '🎯', lvl: 54, cost: 3, min: 4, max: 7, d: [4,4], d2: [4,4], el: 'Air', el2: 'Feu', los: true, type: 'dmg', desc: 'Double frappe Air + Feu' },
      { id: 'destructrice', n: 'Flèche Destructrice', i: '☄️', lvl: 60, cost: 4, min: 4, max: 7, d: [8,10], el: 'Terre', los: true, type: 'dmg', desc: 'Grosse flèche Terre' },
      { id: 'absorbante', n: 'Flèche Absorbante', i: '🩸', lvl: 70, cost: 4, min: 4, max: 7, d: [9,12], el: 'Air', los: true, type: 'dmg', steal: 1, desc: 'Dégâts Air, vole 100% des dégâts en PV' },
      { id: 'ralentissante', n: 'Flèche Ralentissante', i: '🐌', lvl: 80, cost: 4, min: 1, max: 8, d: [7,8], el: 'Eau', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Eau, cible esquive moins les PA' },
      { id: 'explosive', n: 'Flèche Explosive', i: '💣', lvl: 90, cost: 4, min: 1, max: 8, d: [7,9], el: 'Feu', los: true, type: 'dmg', aoe: 1, desc: 'Dégâts Feu en zone (rayon 1)' },
      { id: 'maitrise', n: "Maîtrise de l'Arc", i: '🏹', lvl: 100, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 20, turns: 3 }, desc: '+20 dégâts pendant 3 tours' }
    ] },
  feca: { n: 'Feca', icon: '🛡️', img: 'clofus.webp', hp: 380, el: 'Eau', mainStat: 'intel',
    stats: { force: 10, intel: 35, chance: 15, agi: 5, vita: 35, sag: 15 },
    res: { Neutre: 5, Terre: 5, Feu: 5, Eau: 15, Air: 5 },
    style: 'ranged', desc: 'Protecteur 1.29. Boucliers élémentaires, glyphes, aveuglement et renvoi de sorts.',
    spells: [
      { id: 's3', n: 'Attaque Naturelle', i: '💧', lvl: 1, cost: 5, min: 1, max: 6, d: [4,8], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's6', n: 'Armure Terrestre', i: '🛡️', lvl: 1, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'vita', vita: { v: 12, turns: 4 }, desc: '+12 PV max pendant 4 tours (bouclier)' },
      { id: 's17', n: 'Glyphe Agressif', i: '✨', lvl: 1, cost: 3, min: 1, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Glyphe Agressif' },
      { id: 's4', n: 'Renvoi de Sort', i: '✨', lvl: 3, cost: 3, min: 0, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Renvoi de Sort' },
      { id: 's2', n: 'Aveuglement', i: '🎯', lvl: 6, cost: 3, min: 1, max: 7, d: [4,8], el: 'Air', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Air, la cible esquive moins les PA' },
      { id: 's1', n: 'Armure Incandescente', i: '🛡️', lvl: 9, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'vita', vita: { v: 17, turns: 4 }, desc: '+17 PV max pendant 4 tours (bouclier)' },
      { id: 's9', n: 'Attaque Nuageuse', i: '💧', lvl: 13, cost: 4, min: 1, max: 6, d: [16,30], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's18', n: 'Armure Aqueuse', i: '🛡️', lvl: 17, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'vita', vita: { v: 20, turns: 4 }, desc: '+20 PV max pendant 4 tours (bouclier)' },
      { id: 's20', n: 'ImmunitÃ© ', i: '✨', lvl: 21, cost: 3, min: 0, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ImmunitÃ© ' },
      { id: 's14', n: 'Armure Venteuse', i: '🛡️', lvl: 26, cost: 2, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'vita', vita: { v: 20, turns: 4 }, desc: '+20 PV max pendant 4 tours (bouclier)' },
      { id: 's19', n: 'Bulle', i: '👊', lvl: 31, cost: 3, min: 4, max: 8, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's5', n: 'TrÃªve', i: '✨', lvl: 36, cost: 4, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'TrÃªve' },
      { id: 's16', n: 'Science du bÃ¢ton', i: '✨', lvl: 42, cost: 2, min: 0, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Science du bÃ¢ton' },
      { id: 's8', n: 'Retour du bÃ¢ton', i: '🌪️', lvl: 48, cost: 3, min: 1, max: 3, d: [16,31], el: 'Air', los: true, type: 'dmg', desc: 'Dégâts Air' },
      { id: 's12', n: 'Glyphe d\\', i: '✨', lvl: 54, cost: 3, min: 0, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Glyphe d\\' },
      { id: 's11', n: 'TÃ©lÃ©portation', i: '🌀', lvl: 60, cost: 4, min: 1, max: 9, el: 'Neutre', los: false, type: 'tp', desc: 'Téléportation en portée 1-9' },
      { id: 's10', n: 'Glyphe EnflammÃ© ', i: '✨', lvl: 70, cost: 3, min: 1, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Glyphe EnflammÃ© ' },
      { id: 's7', n: 'Bouclier FÃ©ca', i: '✨', lvl: 80, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Bouclier FÃ©ca' },
      { id: 's15', n: 'Glyphe d\\', i: '✨', lvl: 90, cost: 3, min: 0, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Glyphe d\\' },
      { id: 's13', n: 'Glyphe de Silence', i: '✨', lvl: 100, cost: 4, min: 0, max: 3, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Glyphe de Silence' }
    ] },
  osa: { n: 'Osamodas', icon: '🐉', img: 'clofus.webp', hp: 340, el: 'Terre', mainStat: 'force',
    stats: { force: 30, intel: 10, chance: 10, agi: 10, vita: 35, sag: 15 },
    res: { Neutre: 5, Terre: 15, Feu: 0, Eau: -5, Air: 0 },
    style: 'ranged', desc: 'Invocateur 1.29. Griffes spectrales, bénédictions animales et invocation de Tofus.',
    spells: [
      { id: 's21', n: 'Griffe Spectrale', i: '💧', lvl: 1, cost: 5, min: 1, max: 5, d: [5,10], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's23', n: 'Cri de l\\', i: '💪', lvl: 1, cost: 3, min: 1, max: 5, el: 'Neutre', los: true, type: 'self', self: 'flat', flat: { v: 10, turns: 3 }, desc: '+10 dégâts pendant 3 tours' },
      { id: 's34', n: 'Invocation de Tofu', i: '🐦', lvl: 1, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Tofu', icon: '🐦', hp: 80, el: 'Air', stats: { force: 5, intel: 5, chance: 10, agi: 25, vita: 10, sag: 5 }, res: { Neutre: 0, Terre: -20, Feu: 0, Eau: 0, Air: 20 } }, desc: 'Invoque un Tofu qui attaque au corps à corps' },
      { id: 's26', n: 'BÃ©nÃ©diction Animale ', i: '✨', lvl: 3, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'BÃ©nÃ©diction Animale ' },
      { id: 's22', n: 'DÃ©placement FÃ©lin', i: '👁️', lvl: 6, cost: 2, min: 1, max: 8, el: 'Neutre', los: true, type: 'self', self: 'rangeUp', desc: '+PM et portée bonus' },
      { id: 's35', n: 'Invocation de Bouftou', i: '🐑', lvl: 9, cost: 4, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Bouftou', icon: '🐑', hp: 100, el: 'Neutre', stats: { force: 15, intel: 5, chance: 5, agi: 5, vita: 15, sag: 5 }, res: { Neutre: 10, Terre: -5, Feu: 0, Eau: 0, Air: 0 } }, desc: 'Invoque un Bouftou qui charge au corps à corps' },
      { id: 's28', n: 'Crapaud', i: '✨', lvl: 13, cost: 1, min: 1, max: 9, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Crapaud' },
      { id: 's37', n: 'Invocation de Prespic', i: '🦔', lvl: 17, cost: 4, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Prespic', icon: '🦔', hp: 90, el: 'Feu', stats: { force: 10, intel: 15, chance: 5, agi: 10, vita: 10, sag: 5 }, res: { Neutre: 0, Terre: 0, Feu: 15, Eau: -10, Air: 0 } }, desc: 'Invoque un Prespic qui crache du feu' },
      { id: 's30', n: 'Fouet', i: '🌪️', lvl: 21, cost: 1, min: 1, max: 10, d: [16,31], el: 'Air', los: false, type: 'dmg', desc: 'Dégâts Air' },
      { id: 's27', n: 'PiqÃ»re Motivante', i: '✨', lvl: 26, cost: 3, min: 1, max: 9, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'PiqÃ»re Motivante' },
      { id: 's24', n: 'Corbeau', i: '💧', lvl: 31, cost: 3, min: 1, max: 9, d: [7,13], el: 'Eau', los: false, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's33', n: 'Griffe Cinglante', i: '👊', lvl: 36, cost: 3, min: 1, max: 8, d: [11,20], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's25', n: 'Soin Animal', i: '✨', lvl: 42, cost: 4, min: 1, max: 9, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Soin Animal' },
      { id: 's38', n: 'Invocation de Sanglier', i: '🐗', lvl: 48, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Sanglier', icon: '🐗', hp: 130, el: 'Neutre', stats: { force: 20, intel: 5, chance: 5, agi: 10, vita: 20, sag: 5 }, res: { Neutre: 5, Terre: 10, Feu: 0, Eau: -5, Air: 0 } }, desc: 'Invoque un Sanglier qui charge et repousse' },
      { id: 's36', n: 'Frappe du Craqueleur', i: '💧', lvl: 54, cost: 4, min: 1, max: 1, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's32', n: 'RÃ©sistance Naturelle', i: '✨', lvl: 60, cost: 1, min: 1, max: 9, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'RÃ©sistance Naturelle' },
      { id: 's29', n: 'Crocs du Mulou', i: '✨', lvl: 70, cost: 2, min: 1, max: 9, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Crocs du Mulou' },
      { id: 's39', n: 'Invocation de Bwork Mage', i: '🧙', lvl: 80, cost: 4, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Bwork Mage', icon: '🧙', hp: 110, el: 'Feu', stats: { force: 5, intel: 20, chance: 5, agi: 10, vita: 10, sag: 5 }, res: { Neutre: 0, Terre: 0, Feu: 20, Eau: -10, Air: 0 } }, desc: 'Invoque un Bwork Mage qui lance des sorts de Feu' },
      { id: 's40', n: 'Invocation de Craqueleur', i: '🪨', lvl: 90, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Craqueleur', icon: '🪨', hp: 160, el: 'Terre', stats: { force: 25, intel: 5, chance: 5, agi: 5, vita: 25, sag: 5 }, res: { Neutre: 5, Terre: 20, Feu: -10, Eau: 5, Air: -10 } }, desc: 'Invoque un Craqueleur, tank de Terre' },
      { id: 's31', n: 'Invocation de Dragonnet Rouge', i: '🐲', lvl: 100, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Dragonnet', icon: '🐲', hp: 140, el: 'Feu', stats: { force: 15, intel: 20, chance: 5, agi: 10, vita: 15, sag: 5 }, res: { Neutre: 0, Terre: -10, Feu: 25, Eau: 0, Air: 0 } }, desc: 'Invoque un Dragonnet Rouge, cracheur de feu puissant' }
    ] },
  enu: { n: 'Enutrof', icon: '🪙', img: 'clofus.webp', hp: 350, el: 'Eau', mainStat: 'chance',
    stats: { force: 10, intel: 10, chance: 35, agi: 10, vita: 30, sag: 15 },
    res: { Neutre: 0, Terre: 0, Feu: 0, Eau: 15, Air: -10 },
    style: 'ranged', desc: 'Chercheur de trésors 1.29. Lancer de pièces/pelles, chance, retrait de PM.',
    spells: [
      { id: 's41', n: 'Sac AnimÃ© ', i: '✨', lvl: 1, cost: 3, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Sac AnimÃ© ' },
      { id: 's43', n: 'Lancer de Pelle', i: '🗿', lvl: 1, cost: 4, min: 1, max: 4, d: [4,8], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's51', n: 'Lancer de PiÃ¨ces', i: '👊', lvl: 1, cost: 2, min: 0, max: 10, d: [4,8], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's49', n: 'Pelle Fantomatique', i: '💧', lvl: 3, cost: 5, min: 0, max: 7, d: [8,15], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's42', n: 'Chance', i: '✨', lvl: 6, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Chance' },
      { id: 's47', n: 'BoÃ®te de Pandore', i: '✨', lvl: 9, cost: 2, min: 0, max: 8, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'BoÃ®te de Pandore' },
      { id: 's48', n: 'Remblai', i: '🗿', lvl: 13, cost: 4, min: 2, max: 8, d: [9,18], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's45', n: 'ClÃ© RÃ©ductrice', i: '✨', lvl: 17, cost: 1, min: 1, max: 10, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'ClÃ© RÃ©ductrice' },
      { id: 's53', n: 'Force de l\\', i: '🔥', lvl: 21, cost: 4, min: 1, max: 4, d: [16,31], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's46', n: 'DÃ©sinvocation', i: '🔥', lvl: 26, cost: 3, min: 1, max: 6, d: [16,31], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's52', n: 'CupiditÃ© ', i: '✨', lvl: 31, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'CupiditÃ© ' },
      { id: 's44', n: 'Roulage de Pelle', i: '💧', lvl: 36, cost: 3, min: 1, max: 8, d: [10,20], el: 'Eau', los: false, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's50', n: 'Maladresse', i: '✨', lvl: 42, cost: 1, min: 1, max: 13, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Maladresse' },
      { id: 's54', n: 'Maladresse de Masse', i: '✨', lvl: 48, cost: 5, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Maladresse de Masse' },
      { id: 's55', n: 'AccÃ©lÃ©ration', i: '👁️', lvl: 54, cost: 3, min: 0, max: 63, el: 'Neutre', los: false, type: 'self', self: 'rangeUp', desc: '+PM et portée bonus' },
      { id: 's56', n: 'Pelle du Jugement', i: '👊', lvl: 60, cost: 4, min: 1, max: 7, d: [14,27], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's58', n: 'Pelle Massacrante', i: '👊', lvl: 70, cost: 5, min: 1, max: 7, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's59', n: 'Corruption', i: '✨', lvl: 80, cost: 6, min: 1, max: 5, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Corruption' },
      { id: 's57', n: 'Pelle AnimÃ©e', i: '✨', lvl: 90, cost: 2, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Pelle AnimÃ©e' },
      { id: 's60', n: 'Coffre AnimÃ© ', i: '✨', lvl: 100, cost: 4, min: 1, max: 8, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Coffre AnimÃ© ' }
    ] },
  sram: { n: 'Sram', icon: '🗡️', img: 'clofus.webp', hp: 330, el: 'Terre', mainStat: 'force',
    stats: { force: 30, intel: 5, chance: 10, agi: 15, vita: 30, sag: 15 },
    res: { Neutre: 5, Terre: 15, Feu: -5, Eau: 0, Air: 5 },
    style: 'melee', desc: 'Assassin 1.29. Sournoiserie, poison, invisibilité et pièges mortels.',
    spells: [
      { id: 's61', n: 'Sournoiserie', i: '🗿', lvl: 1, cost: 4, min: 1, max: 3, d: [3,5], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's65', n: 'PiÃ¨ge Sournois', i: '✨', lvl: 1, cost: 2, min: 1, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge Sournois' },
      { id: 's72', n: 'InvisibilitÃ© ', i: '👁️', lvl: 1, cost: 2, min: 0, max: 0, el: 'Neutre', los: true, type: 'self', self: 'rangeUp', desc: '+PM et portée bonus' },
      { id: 's66', n: 'Poison insidieux', i: '🔥', lvl: 3, cost: 3, min: 1, max: 4, d: [4,7], el: 'Feu', los: false, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's68', n: 'Fourvoiement', i: '🔥', lvl: 6, cost: 5, min: 0, max: 0, d: [12,22], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's63', n: 'Coup Sournois', i: '🗿', lvl: 9, cost: 3, min: 1, max: 1, d: [12,24], el: 'Terre', los: true, type: 'dmg', push: 2, desc: 'Dégâts Terre, + repousse de 2' },
      { id: 's74', n: 'Double', i: '✨', lvl: 13, cost: 2, min: 1, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Double' },
      { id: 's64', n: 'RepÃ©rage', i: '✨', lvl: 17, cost: 2, min: 0, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'RepÃ©rage' },
      { id: 's79', n: 'PiÃ¨ge de Masse', i: '✨', lvl: 21, cost: 4, min: 1, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge de Masse' },
      { id: 's78', n: 'InvisibilitÃ© d\\', i: '✨', lvl: 26, cost: 2, min: 1, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'InvisibilitÃ© d\\' },
      { id: 's71', n: 'PiÃ¨ge EmpoisonnÃ© ', i: '✨', lvl: 31, cost: 3, min: 1, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge EmpoisonnÃ© ' },
      { id: 's62', n: 'Concentration de Chakra', i: '✨', lvl: 36, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Concentration de Chakra' },
      { id: 's69', n: 'PiÃ¨ge d\\', i: '✨', lvl: 42, cost: 4, min: 1, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge d\\' },
      { id: 's77', n: 'PiÃ¨ge de Silence', i: '✨', lvl: 48, cost: 3, min: 1, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge de Silence' },
      { id: 's73', n: 'PiÃ¨ge rÃ©pulsif', i: '✨', lvl: 54, cost: 3, min: 1, max: 7, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge rÃ©pulsif' },
      { id: 's67', n: 'Peur', i: '✨', lvl: 60, cost: 2, min: 2, max: 7, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Peur' },
      { id: 's70', n: 'Arnaque', i: '🔥', lvl: 70, cost: 3, min: 1, max: 3, d: [16,31], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's75', n: 'Pulsion de Chakra', i: '✨', lvl: 80, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Pulsion de Chakra' },
      { id: 's76', n: 'Attaque Mortelle', i: '🗿', lvl: 90, cost: 4, min: 1, max: 2, d: [16,31], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's80', n: 'PiÃ¨ge Mortel', i: '✨', lvl: 100, cost: 3, min: 1, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'PiÃ¨ge Mortel' }
    ] },
  xelor: { n: 'Xelor', icon: '⏳', img: 'clofus.webp', hp: 320, el: 'Feu', mainStat: 'intel',
    stats: { force: 5, intel: 30, chance: 10, agi: 15, vita: 30, sag: 20 },
    res: { Neutre: 0, Terre: 0, Feu: 15, Eau: -10, Air: 5 },
    style: 'ranged', desc: 'Mage temporel 1.29. Ralentissement, retrait de PA, aiguilles et sabliers.',
    spells: [
      { id: 's81', n: 'Ralentissement', i: '✨', lvl: 1, cost: 1, min: 3, max: 4, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Ralentissement' },
      { id: 's82', n: 'Contre', i: '✨', lvl: 1, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Contre' },
      { id: 's83', n: 'Aiguille', i: '💧', lvl: 1, cost: 6, min: 1, max: 6, d: [7,13], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's84', n: 'Gelure', i: '🎯', lvl: 3, cost: 4, min: 3, max: 6, d: [9,17], el: 'Feu', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Feu, la cible esquive moins les PA' },
      { id: 's100', n: 'Sablier de XÃ©lor', i: '🎯', lvl: 6, cost: 2, min: 3, max: 6, d: [6,11], el: 'Eau', los: false, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Eau, la cible esquive moins les PA' },
      { id: 's92', n: 'Rayon Obscur', i: '💧', lvl: 9, cost: 4, min: 1, max: 9, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's88', n: 'TÃ©lÃ©portation', i: '🌀', lvl: 13, cost: 4, min: 1, max: 63, el: 'Neutre', los: false, type: 'tp', desc: 'Téléportation en portée 1-63' },
      { id: 's93', n: 'FlÃ©trissement ', i: '🔥', lvl: 17, cost: 3, min: 1, max: 8, d: [16,30], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's85', n: 'Flou', i: '✨', lvl: 21, cost: 3, min: 4, max: 4, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Flou' },
      { id: 's96', n: 'PoussiÃ¨re Temporelle ', i: '🎯', lvl: 26, cost: 5, min: 0, max: 7, d: [14,26], el: 'Eau', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Eau, la cible esquive moins les PA' },
      { id: 's98', n: 'Vol du Temps', i: '✨', lvl: 31, cost: 4, min: 3, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Vol du Temps' },
      { id: 's86', n: 'Aiguille Chercheuse', i: '✨', lvl: 36, cost: 3, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Aiguille Chercheuse' },
      { id: 's89', n: 'DÃ©vouement', i: '✨', lvl: 42, cost: 2, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'DÃ©vouement' },
      { id: 's90', n: 'Fuite', i: '🌀', lvl: 48, cost: 1, min: 1, max: 1, el: 'Neutre', los: false, type: 'tp', desc: 'Téléportation en portée 1-1' },
      { id: 's87', n: 'DÃ©motivation', i: '✨', lvl: 54, cost: 1, min: 1, max: 14, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'DÃ©motivation' },
      { id: 's94', n: 'Protection Aveuglante', i: '✨', lvl: 60, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Protection Aveuglante' },
      { id: 's99', n: 'Momification', i: '💪', lvl: 70, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 4, turns: 3 }, desc: '+4 dégâts pendant 3 tours' },
      { id: 's95', n: 'Horloge', i: '👊', lvl: 80, cost: 4, min: 1, max: 4, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's91', n: 'Frappe de XÃ©lor', i: '🗿', lvl: 90, cost: 4, min: 1, max: 5, d: [16,31], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's97', n: 'Cadran de XÃ©lor', i: '✨', lvl: 100, cost: 1, min: 1, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Cadran de XÃ©lor' }
    ] },
  eca: { n: 'Ecaflip', icon: '🎲', img: 'clofus.webp', hp: 350, el: 'Feu', mainStat: 'chance',
    stats: { force: 10, intel: 10, chance: 30, agi: 15, vita: 30, sag: 15 },
    res: { Neutre: 10, Terre: 0, Feu: 10, Eau: 5, Air: 5 },
    style: 'melee', desc: 'Joueur 1.29. Pile ou face, chance aléatoire (soin/dégâts), bond félin.',
    spells: [
      { id: 's102', n: 'Pile ou Face', i: '🗿', lvl: 1, cost: 3, min: 0, max: 5, d: [5,10], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's103', n: 'Chance d\\', i: '✨', lvl: 1, cost: 2, min: 0, max: 2, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Chance d\\' },
      { id: 's105', n: 'Bond du FÃ©lin', i: '🌀', lvl: 1, cost: 2, min: 1, max: 1, el: 'Neutre', los: true, type: 'tp', desc: 'Téléportation en portée 1-1' },
      { id: 's109', n: 'Bluff', i: '👊', lvl: 3, cost: 4, min: 1, max: 4, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's113', n: 'Perception', i: '💪', lvl: 6, cost: 2, min: 0, max: 0, el: 'Neutre', los: true, type: 'self', self: 'flat', flat: { v: 7, turns: 3 }, desc: '+7 dégâts pendant 3 tours' },
      { id: 's111', n: 'Contrecoup', i: '✨', lvl: 9, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Contrecoup' },
      { id: 's104', n: 'TrÃ¨fle', i: '✨', lvl: 13, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'TrÃ¨fle' },
      { id: 's119', n: 'Tout ou rien', i: '🌪️', lvl: 17, cost: 3, min: 0, max: 0, d: [16,31], el: 'Air', los: false, type: 'dmg', desc: 'Dégâts Air' },
      { id: 's101', n: 'Roulette', i: '💪', lvl: 21, cost: 1, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 65, turns: 3 }, desc: '+65 dégâts pendant 3 tours' },
      { id: 's107', n: 'Topkaj', i: '💧', lvl: 26, cost: 3, min: 1, max: 5, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's116', n: 'Langue RÃ¢peuse ', i: '💧', lvl: 31, cost: 4, min: 1, max: 4, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's106', n: 'Roue de la Fortune', i: '✨', lvl: 36, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Roue de la Fortune' },
      { id: 's117', n: 'Griffe Invocatrice', i: '✨', lvl: 42, cost: 3, min: 1, max: 4, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Griffe Invocatrice' },
      { id: 's108', n: 'Esprit FÃ©lin', i: '🗿', lvl: 48, cost: 3, min: 1, max: 1, d: [16,31], el: 'Terre', los: false, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's115', n: 'Odorat', i: '👁️', lvl: 54, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'rangeUp', desc: '+PM et portée bonus' },
      { id: 's118', n: 'RÃ©flexes', i: '✨', lvl: 60, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'RÃ©flexes' },
      { id: 's110', n: 'Griffe Joueuse', i: '🗿', lvl: 70, cost: 4, min: 1, max: 4, d: [16,31], el: 'Terre', los: false, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's112', n: 'Griffe de Ceangal', i: '🗿', lvl: 80, cost: 4, min: 1, max: 1, d: [16,31], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's114', n: 'Rekop', i: '🎯', lvl: 90, cost: 4, min: 1, max: 4, d: [16,31], el: 'Neutre', los: true, type: 'dmg', paDodgeDown: true, desc: 'Dégâts Neutre, la cible esquive moins les PA' },
      { id: 's120', n: 'Destin d\\', i: '🗿', lvl: 100, cost: 4, min: 1, max: 1, d: [16,31], el: 'Terre', los: true, type: 'dmg', push: 1, desc: 'Dégâts Terre, + repousse de 1' }
    ] },
  eni: { n: 'Eniripsa', icon: '🧚', img: 'clofus.webp', hp: 310, el: 'Feu', mainStat: 'intel',
    stats: { force: 5, intel: 35, chance: 10, agi: 10, vita: 30, sag: 15 },
    res: { Neutre: 5, Terre: 0, Feu: 15, Eau: 5, Air: -10 },
    style: 'ranged', desc: 'Soigneur 1.29. Mots curatifs, soins puissants, mot de frayeur (repousse).',
    spells: [
      { id: 's121', n: 'Mot Curatif', i: '💚', lvl: 1, cost: 6, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'heal', desc: 'Soigne 8-14 PV' },
      { id: 's125', n: 'Mot Interdit', i: '💧', lvl: 1, cost: 6, min: 1, max: 4, d: [6,12], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's128', n: 'Mot de Frayeur', i: '💨', lvl: 1, cost: 2, min: 1, max: 2, el: 'Neutre', los: true, type: 'push', push: 1, desc: 'Repousse de 1 case' },
      { id: 's124', n: 'Mot Soignant', i: '💚', lvl: 3, cost: 3, min: 1, max: 5, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 7-13 PV' },
      { id: 's122', n: 'Mot Blessant', i: '🔥', lvl: 6, cost: 3, min: 1, max: 7, d: [10,20], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's126', n: 'Mot Stimulant', i: '✨', lvl: 9, cost: 2, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot Stimulant' },
      { id: 's127', n: 'Mot de PrÃ©vention', i: '✨', lvl: 13, cost: 3, min: 0, max: 7, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Mot de PrÃ©vention' },
      { id: 's123', n: 'Mot Drainant', i: '✨', lvl: 17, cost: 2, min: 1, max: 12, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot Drainant' },
      { id: 's130', n: 'Mot Revitalisant', i: '💚', lvl: 21, cost: 2, min: 0, max: 4, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 7-13 PV' },
      { id: 's131', n: 'Mot de RÃ©gÃ©nÃ©ration', i: '💚', lvl: 26, cost: 3, min: 0, max: 3, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 3-6 PV' },
      { id: 's132', n: 'Mot d\\', i: '✨', lvl: 31, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Mot d\\' },
      { id: 's133', n: 'Mot de Jouvence', i: '✨', lvl: 36, cost: 3, min: 0, max: 11, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot de Jouvence' },
      { id: 's134', n: 'Mot Vampirique', i: '✨', lvl: 42, cost: 4, min: 0, max: 4, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot Vampirique' },
      { id: 's135', n: 'Mot de Sacrifice', i: '💚', lvl: 48, cost: 4, min: 1, max: 6, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 31-52 PV' },
      { id: 's129', n: 'Mot d\\', i: '✨', lvl: 54, cost: 3, min: 1, max: 3, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot d\\' },
      { id: 's136', n: 'Mot d\\', i: '✨', lvl: 60, cost: 3, min: 1, max: 8, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot d\\' },
      { id: 's137', n: 'Mot d\\', i: '✨', lvl: 70, cost: 1, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot d\\' },
      { id: 's138', n: 'Mot de Silence', i: '✨', lvl: 80, cost: 3, min: 0, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Mot de Silence' },
      { id: 's139', n: 'Mot d\\', i: '💚', lvl: 90, cost: 6, min: 0, max: 0, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 39-65 PV' },
      { id: 's140', n: 'Mot de Reconstitution', i: '💚', lvl: 100, cost: 4, min: 0, max: 7, el: 'Neutre', los: true, type: 'self', self: 'heal', desc: 'Soigne 39-65 PV' }
    ] },
  sadi: { n: 'Sadida', icon: '🌿', img: 'clofus.webp', hp: 340, el: 'Terre', mainStat: 'force',
    stats: { force: 30, intel: 10, chance: 10, agi: 10, vita: 35, sag: 15 },
    res: { Neutre: 5, Terre: 15, Feu: -5, Eau: 5, Air: 0 },
    style: 'ranged', desc: 'Invokeur nature 1.29. Ronces, poison paralysant, larmes et sacrifice poupesque.',
    spells: [
      { id: 's183', n: 'Ronce', i: '🗿', lvl: 1, cost: 5, min: 1, max: 6, d: [4,8], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's193', n: 'La Bloqueuse', i: '🪆', lvl: 1, cost: 5, min: 0, max: 0, el: 'Neutre', los: false, type: 'summon', summon: { n: 'Poupée', icon: '🪆', hp: 60, el: 'Neutre', stats: { force: 15, intel: 5, chance: 5, agi: 5, vita: 10, sag: 5 }, res: { Neutre: 10, Terre: 10, Feu: -10, Eau: 0, Air: 0 } }, desc: 'Invoque une poupée bloqueuse qui tank les dégâts' },
      { id: 's200', n: 'Poison Paralysant', i: '🪤', lvl: 1, cost: 3, min: 1, max: 4, d: [3,3], el: 'Neutre', los: true, type: 'dmg', slow: true, desc: 'Dégâts Neutre, immobilise la cible (-1 PM)' },
      { id: 's198', n: 'Sacrifice Poupesque', i: '✨', lvl: 3, cost: 5, min: 1, max: 2, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Sacrifice Poupesque' },
      { id: 's195', n: 'Larme', i: '👊', lvl: 6, cost: 4, min: 1, max: 6, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's182', n: 'La Folle', i: '✨', lvl: 9, cost: 3, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'La Folle' },
      { id: 's192', n: 'Ronce Apaisante', i: '✨', lvl: 13, cost: 2, min: 1, max: 8, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Ronce Apaisante' },
      { id: 's197', n: 'Puissance Sylvestre', i: '✨', lvl: 17, cost: 2, min: 0, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Puissance Sylvestre' },
      { id: 's189', n: 'La SacrifiÃ©e', i: '✨', lvl: 21, cost: 2, min: 1, max: 2, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'La SacrifiÃ©e' },
      { id: 's181', n: 'Tremblement', i: '💧', lvl: 26, cost: 2, min: 0, max: 0, d: [7,14], el: 'Eau', los: false, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's199', n: 'Connaissance des PoupÃ©es', i: '✨', lvl: 31, cost: 2, min: 0, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Connaissance des PoupÃ©es' },
      { id: 's191', n: 'Ronces Multiples', i: '🗿', lvl: 36, cost: 3, min: 0, max: 7, d: [14,27], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's186', n: 'Arbre', i: '✨', lvl: 42, cost: 3, min: 1, max: 6, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Arbre' },
      { id: 's196', n: 'Vent EmpoisonnÃ© ', i: '🌪️', lvl: 48, cost: 3, min: 0, max: 0, d: [7,13], el: 'Air', los: false, type: 'dmg', desc: 'Dégâts Air' },
      { id: 's190', n: 'La Gonflable', i: '✨', lvl: 54, cost: 4, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'La Gonflable' },
      { id: 's194', n: 'Ronces Agressives ', i: '🗿', lvl: 60, cost: 4, min: 1, max: 7, d: [16,31], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's185', n: 'Herbe Folle', i: '💧', lvl: 70, cost: 3, min: 0, max: 8, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's184', n: 'Feu de Brousse', i: '💧', lvl: 80, cost: 3, min: 1, max: 7, d: [16,29], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's188', n: 'Ronce Insolente', i: '✨', lvl: 90, cost: 3, min: 0, max: 12, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Ronce Insolente' },
      { id: 's187', n: 'La Surpuissante', i: '✨', lvl: 100, cost: 3, min: 1, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'La Surpuissante' }
    ] },
  sacri: { n: 'Sacrieur', icon: '😤', img: 'clofus.webp', hp: 420, el: 'Terre', mainStat: 'force',
    stats: { force: 35, intel: 5, chance: 5, agi: 10, vita: 40, sag: 10 },
    res: { Neutre: 5, Terre: 10, Feu: 5, Eau: 5, Air: 5 },
    style: 'melee', desc: 'Berserker 1.29. Plus il souffre, plus il frappe fort. Attire et punit.',
    spells: [
      { id: 's432', n: 'Pied du Sacrieur', i: '🗿', lvl: 1, cost: 4, min: 1, max: 1, d: [6,12], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's433', n: 'ChÃ¢timent OsÃ© ', i: '✨', lvl: 1, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ChÃ¢timent OsÃ© ' },
      { id: 's434', n: 'Attirance', i: '✨', lvl: 1, cost: 3, min: 2, max: 11, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Attirance' },
      { id: 's444', n: 'DÃ©robade', i: '✨', lvl: 3, cost: 3, min: 0, max: 4, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'DÃ©robade' },
      { id: 's449', n: 'DÃ©tour', i: '✨', lvl: 6, cost: 2, min: 1, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'DÃ©tour' },
      { id: 's436', n: 'Assaut', i: '🔥', lvl: 9, cost: 3, min: 1, max: 3, d: [14,27], el: 'Feu', los: true, type: 'dmg', desc: 'Dégâts Feu' },
      { id: 's437', n: 'ChÃ¢timent Agile', i: '✨', lvl: 13, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ChÃ¢timent Agile' },
      { id: 's439', n: 'Dissolution', i: '✨', lvl: 17, cost: 4, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Dissolution' },
      { id: 's431', n: 'ChÃ¢timent ForcÃ© ', i: '✨', lvl: 21, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ChÃ¢timent ForcÃ© ' },
      { id: 's443', n: 'ChÃ¢timent Spirituel', i: '✨', lvl: 26, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ChÃ¢timent Spirituel' },
      { id: 's440', n: 'Sacrifice', i: '✨', lvl: 31, cost: 3, min: 1, max: 5, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Sacrifice' },
      { id: 's442', n: 'Absorption', i: '✨', lvl: 36, cost: 4, min: 1, max: 3, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Absorption' },
      { id: 's441', n: 'ChÃ¢timent Vitalesque', i: '✨', lvl: 42, cost: 3, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'ChÃ¢timent Vitalesque' },
      { id: 's445', n: 'CoopÃ©ration', i: '✨', lvl: 48, cost: 4, min: 1, max: 10, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'CoopÃ©ration' },
      { id: 's438', n: 'Transposition', i: '✨', lvl: 54, cost: 4, min: 1, max: 10, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Transposition' },
      { id: 's446', n: 'Punition', i: '✨', lvl: 60, cost: 4, min: 1, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Punition' },
      { id: 's447', n: 'Furie', i: '☠️', lvl: 70, cost: 3, min: 1, max: 3, d: [10,18], el: 'Neutre', los: true, type: 'dmg', poison: { d: 4, turns: 2 }, desc: 'Dégâts Neutre + poison 11 PV/tour x2' },
      { id: 's448', n: 'EpÃ©e volante', i: '✨', lvl: 80, cost: 4, min: 1, max: 3, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'EpÃ©e volante' },
      { id: 's435', n: 'Transfert de Vie', i: '✨', lvl: 90, cost: 2, min: 0, max: 0, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Transfert de Vie' },
      { id: 's450', n: 'Folie sanguinaire', i: '✨', lvl: 100, cost: 1, min: 1, max: 7, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Folie sanguinaire' }
    ] },
  panda: { n: 'Pandawa', icon: '🐼', img: 'clofus.webp', hp: 380, el: 'Neutre', mainStat: 'force',
    stats: { force: 30, intel: 10, chance: 10, agi: 10, vita: 35, sag: 10 },
    res: { Neutre: 10, Terre: 5, Feu: 10, Eau: -5, Air: 0 },
    style: 'melee', desc: 'Combattant ivre 1.29. Picole, poings enflammés, épouvante et souffle alcoolisé.',
    spells: [
      { id: 's686', n: 'Picole', i: '✨', lvl: 1, cost: 5, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Picole' },
      { id: 's687', n: 'Poing EnflammÃ© ', i: '💧', lvl: 1, cost: 5, min: 1, max: 1, d: [8,15], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's692', n: 'Gueule de Bois', i: '🗿', lvl: 1, cost: 5, min: 1, max: 1, d: [9,17], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's689', n: 'Epouvante', i: '💨', lvl: 3, cost: 3, min: 1, max: 5, el: 'Neutre', los: true, type: 'push', push: 1, desc: 'Repousse de 1 case' },
      { id: 's690', n: 'Souffle AlcoolisÃ© ', i: '🔥', lvl: 6, cost: 4, min: 1, max: 5, d: [12,24], el: 'Feu', los: true, type: 'dmg', push: 2, desc: 'Dégâts Feu, + repousse de 2' },
      { id: 's691', n: 'VulnÃ©rabilitÃ© Aqueuse', i: '✨', lvl: 9, cost: 2, min: 1, max: 7, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'VulnÃ©rabilitÃ© Aqueuse' },
      { id: 's688', n: 'VulnÃ©rabilitÃ© Incandescente', i: '✨', lvl: 13, cost: 2, min: 1, max: 7, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'VulnÃ©rabilitÃ© Incandescente' },
      { id: 's693', n: 'Karcham', i: '✨', lvl: 17, cost: 1, min: 1, max: 1, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Karcham' },
      { id: 's694', n: 'VulnÃ©rabilitÃ© Venteuse', i: '✨', lvl: 21, cost: 2, min: 1, max: 7, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'VulnÃ©rabilitÃ© Venteuse' },
      { id: 's695', n: 'Stabilisation', i: '✨', lvl: 26, cost: 2, min: 0, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Stabilisation' },
      { id: 's696', n: 'Chamrak', i: '✨', lvl: 31, cost: 1, min: 1, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Chamrak' },
      { id: 's697', n: 'VulnÃ©rabilitÃ© Terrestre', i: '✨', lvl: 36, cost: 2, min: 1, max: 7, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'VulnÃ©rabilitÃ© Terrestre' },
      { id: 's698', n: 'Souillure', i: '✨', lvl: 42, cost: 2, min: 1, max: 1, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Souillure' },
      { id: 's699', n: 'Lait de Bambou', i: '✨', lvl: 48, cost: 1, min: 0, max: 0, d: [3,6], el: 'Neutre', los: true, type: 'dmg', desc: 'Lait de Bambou' },
      { id: 's700', n: 'Vague ÃƒÂ  Lame', i: '👊', lvl: 54, cost: 4, min: 1, max: 5, d: [16,31], el: 'Neutre', los: true, type: 'dmg', desc: 'Dégâts Neutre' },
      { id: 's701', n: 'ColÃ¨re de ZatoÃƒÂ¯shwan', i: '💪', lvl: 60, cost: 6, min: 0, max: 0, el: 'Neutre', los: false, type: 'self', self: 'flat', flat: { v: 10, turns: 3 }, desc: '+10 dégâts pendant 3 tours' },
      { id: 's702', n: 'Flasque Explosive', i: '💧', lvl: 70, cost: 2, min: 2, max: 5, d: [16,31], el: 'Eau', los: true, type: 'dmg', desc: 'Dégâts Eau' },
      { id: 's703', n: 'Pandatak', i: '🗿', lvl: 80, cost: 4, min: 1, max: 6, d: [16,31], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' },
      { id: 's704', n: 'Pandanlku', i: '👁️', lvl: 90, cost: 2, min: 0, max: 6, el: 'Neutre', los: true, type: 'self', self: 'rangeUp', desc: '+PM et portée bonus' },
      { id: 's705', n: 'Lien Spiritueux', i: '✨', lvl: 100, cost: 2, min: 1, max: 6, d: [3,6], el: 'Neutre', los: false, type: 'dmg', desc: 'Lien Spiritueux' }
    ] },
};

var ADVERSARIES = {
  feca: Object.assign({}, CLASSES.feca, { desc: 'Adversaire Feca niv 200. Tous les sorts débloqués.' }),
  osa: Object.assign({}, CLASSES.osa, { desc: 'Adversaire Osamodas niv 200. Tous les sorts débloqués.' }),
  enu: Object.assign({}, CLASSES.enu, { desc: 'Adversaire Enutrof niv 200. Tous les sorts débloqués.' }),
  sram: Object.assign({}, CLASSES.sram, { desc: 'Adversaire Sram niv 200. Tous les sorts débloqués.' }),
  xelor: Object.assign({}, CLASSES.xelor, { desc: 'Adversaire Xelor niv 200. Tous les sorts débloqués.' }),
  eca: Object.assign({}, CLASSES.eca, { desc: 'Adversaire Ecaflip niv 200. Tous les sorts débloqués.' }),
  eni: Object.assign({}, CLASSES.eni, { desc: 'Adversaire Eniripsa niv 200. Tous les sorts débloqués.' }),
  iop: Object.assign({}, CLASSES.iop, { desc: 'Adversaire Iop niv 200. Tous les sorts débloqués.' }),
  cra: Object.assign({}, CLASSES.cra, { desc: 'Adversaire Cra niv 200. Tous les sorts débloqués.' }),
  sadi: Object.assign({}, CLASSES.sadi, { desc: 'Adversaire Sadida niv 200. Tous les sorts débloqués.' }),
  sacri: Object.assign({}, CLASSES.sacri, { desc: 'Adversaire Sacrieur niv 200. Tous les sorts débloqués.' }),
  panda: Object.assign({}, CLASSES.panda, { desc: 'Adversaire Pandawa niv 200. Tous les sorts débloqués.' }),
};

/* ---------------- Monstres 1.29 (données réelles GDCore) ---------------- */

var MONSTRES = {
  larve: { n: 'Larve Bleue', icon: '🐛', img: 'minogolem-green.webp', hp: 120, el: 'Eau', mainStat: 'agi',
    stats: { force: 10, intel: 10, chance: 20, agi: 20, vita: 20, sag: 5 },
    res: { Neutre: 0, Terre: -20, Feu: 0, Eau: 10, Air: 0 },
    style: 'melee', ia: 'attack',
    desc: "Petit monstre d'Amakna. Mords (Terre) et crache (Eau) en affaiblissant l'esquive.",
    spells: [
      { id: 'morsure', n: 'Morsure', i: '🦷', lvl: 1, cost: 3, min: 1, max: 1, d: [4,7], el: 'Terre', los: true, type: 'dmg', desc: 'Morsure Terre' },
      { id: 'crachat', n: 'Crachat', i: '💧', lvl: 1, cost: 3, min: 1, max: 6, d: [3,4], el: 'Eau', los: true, type: 'dmg', paDodgeDown: true, desc: 'Crachat Eau, cible esquive moins les PA' }
    ] },
  tofu: { n: 'Tofu', icon: '🐦', img: 'minogolem-grey.webp', hp: 100, el: 'Air', mainStat: 'agi',
    stats: { force: 5, intel: 5, chance: 10, agi: 35, vita: 15, sag: 5 },
    res: { Neutre: 0, Terre: -20, Feu: 0, Eau: 0, Air: 20 },
    style: 'ranged', ia: 'flee',
    desc: "Oiseau agressif d'Amakna. Frappe à l'Air et fuit le contact.",
    spells: [
      { id: 'piqure', n: 'Piqure', i: '🪶', lvl: 1, cost: 4, min: 1, max: 3, d: [5,8], el: 'Air', los: true, type: 'dmg', paDodgeDown: true, desc: 'Piqure Air + -esquive PA' }
    ] },
  bouftou: { n: 'Bouftou', icon: '🐑', img: 'minogolem-blue.webp', hp: 200, el: 'Neutre', mainStat: 'force',
    stats: { force: 30, intel: 5, chance: 5, agi: 5, vita: 40, sag: 5 },
    res: { Neutre: 10, Terre: -10, Feu: 0, Eau: 0, Air: 0 },
    style: 'melee', ia: 'attack',
    desc: "Le mouton d'Amakna. Charge et frappe fort au Neutre.",
    spells: [
      { id: 'coup', n: 'Coup de Bouftou', i: '🐏', lvl: 1, cost: 4, min: 1, max: 1, d: [8,11], el: 'Neutre', los: true, type: 'dmg', desc: 'Coup Neutre' }
    ] },
  sanglier: { n: 'Sanglier', icon: '🐗', img: 'minogolem-red.webp', hp: 180, el: 'Neutre', mainStat: 'force',
    stats: { force: 35, intel: 5, chance: 5, agi: 10, vita: 30, sag: 5 },
    res: { Neutre: 0, Terre: 10, Feu: 0, Eau: 0, Air: -10 },
    style: 'melee', ia: 'attack',
    desc: 'Charge sauvage : dégâts Neutre et te repousse.',
    spells: [
      { id: 'charge', n: 'Charge', i: '💨', lvl: 1, cost: 4, min: 1, max: 1, d: [6,9], el: 'Neutre', los: true, type: 'dmg', push: 1, desc: 'Dégâts Neutre + repousse 1 case' }
    ] },
  wabbit: { n: 'Wabbit', icon: '🐰', img: 'minogolem-green.webp', hp: 220, el: 'Terre', mainStat: 'force',
    stats: { force: 25, intel: 5, chance: 10, agi: 15, vita: 35, sag: 5 },
    res: { Neutre: 0, Terre: 10, Feu: -10, Eau: 0, Air: 0 },
    style: 'melee', ia: 'attack',
    desc: 'Lapin-guerrier. Frappe à la Terre.',
    spells: [
      { id: 'coup_patte', n: 'Coup de patte', i: '🥊', lvl: 1, cost: 3, min: 1, max: 1, d: [5,8], el: 'Terre', los: true, type: 'dmg', desc: 'Coup Terre' }
    ] },
  chafer: { n: 'Chafer', icon: '💀', img: 'minogolem-grey.webp', hp: 320, el: 'Terre', mainStat: 'force',
    stats: { force: 45, intel: 5, chance: 5, agi: 10, vita: 50, sag: 10 },
    res: { Neutre: 0, Terre: 20, Feu: -20, Eau: 0, Air: 0 },
    style: 'melee', ia: 'attack',
    desc: 'Squelette soldat des Chafers. Frappe Terre très lourd.',
    spells: [
      { id: 'epee_chafer', n: 'Épée du Chafer', i: '⚔️', lvl: 1, cost: 3, min: 1, max: 1, d: [12,16], el: 'Terre', los: true, type: 'dmg', desc: 'Dégâts Terre' }
    ] },
  royal: { n: 'Bouftou Royal', icon: '👑', img: 'minogolem-red.webp', hp: 400, el: 'Neutre', mainStat: 'force',
    stats: { force: 50, intel: 10, chance: 10, agi: 5, vita: 60, sag: 15 },
    res: { Neutre: 10, Terre: 20, Feu: 0, Eau: 0, Air: -20 },
    style: 'melee', ia: 'heal',
    desc: "Le boss d'Amakna. Se soigne, frappe et écrase très fort.",
    spells: [
      { id: 'soin', n: 'Bêlement Soignant', i: '💚', lvl: 1, cost: 3, min: 0, max: 0, d: [16,24], el: 'Neutre', los: false, type: 'self', self: 'heal', desc: 'Se soigne de 40-60 PV' },
      { id: 'coup_royal', n: 'Coup Royal', i: '🐏', lvl: 1, cost: 4, min: 1, max: 1, d: [12,16], el: 'Neutre', los: true, type: 'dmg', desc: 'Coup Neutre' },
      { id: 'ecrase', n: 'Écrasement', i: '💥', lvl: 1, cost: 3, min: 1, max: 4, d: [36,48], el: 'Neutre', los: true, type: 'dmg', desc: 'Écrasement Neutre dévastateur' }
    ] }
};

// Monstres disponibles comme adversaires (IA : attack par défaut)
ADVERSARIES.larve = MONSTRES.larve;
ADVERSARIES.tofu = MONSTRES.tofu;
ADVERSARIES.bouftou = MONSTRES.bouftou;
ADVERSARIES.sanglier = MONSTRES.sanglier;
ADVERSARIES.wabbit = MONSTRES.wabbit;
ADVERSARIES.chafer = MONSTRES.chafer;
ADVERSARIES.royal = MONSTRES.royal;
